### ISSUE TITLE
Preparation for AMA #1 with Chainlink Indonesia

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/ama-with-cross-chain-communities#3]
## To-do list
- [x] Decided to have Chainlink for the 1st AMA
- [x] Contact Chainlink Indonesia Ambassador, Juan Karamoy
- [x] Make a group at telegram to connect and coordinating for the event
- [x] Agree on the date of the AMA (Saturday, 13 November 2022 at 19:00-21:00 WIB)
- [x] Find speaker(s) from Cardano Indonesia community
- [x] Coordinating about the material for AMA with speakers from Chainlink Indonesia
- [x] Coordinating about the material for AMA with speakers from Cardano Indonesia
- [x] Tell @stevaniongko99 to finish the design for marketing by October 20th, 2022
- [x]  Make a detail rundown for the AMA
- [x] Create Meetup event @andreassosilo 
- [x] Flyer created by Stevani

## Discussion

- Try to ask Andre Cahyadi or Dion Setyotomo to become speaker from Cardano Indonesia
- Meetup event @andreassosilo will add @ivankwan88 as event organizer in Cardano Blockchain Jakarta
- Meetup event for AMA Cross-Chain with Chainlink created. See [here](https://www.meetup.com/cardano-blockchain-jakarta/events/289062913)

**Comment by ivankwan88** [comment]
done
