### ISSUE TITLE
Submit Monthly KPI Report - October 2022

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/ama-with-cross-chain-communities#4]
**Tasks:**

- [x]  Fill monthly KPI report for AMA with Cross-Chain Communities - Oct 2022
- [x]  Submit the Google Forms
- [x] Check in [Public MVP Report](https://docs.google.com/spreadsheets/d/1bfnWFa94Y7Zj0G7dtpo9W1nAYGovJbswipxiHT4UE3g/edit#gid=917336114)

**Comment by andreassosilo** [comment]
Done. Closed.
