### ISSUE TITLE
Preparation for AMA #2 with Harmony Indonesia

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/ama-with-cross-chain-communities#7]
## To-do list
- [x] Decided to have Harmony for the 2st AMA
- [x] Contact Harmony Indonesia
- [x] Make a group at whatsup to connect and coordinating for the event
- [x] Agree on the date of the AMA (Sunday, 11 December 2022 at 19:00-21:00 WIB)
- [x] Find speaker(s) from Cardano Indonesia community
- [ ] Coordinating about the material for AMA with speakers from Cardano Indonesia
- [ ] Coordinating about the material for AMA with speakers from Harmony Indonesia
- [ ] Tell @stevaniongko99 to finish the design for marketing by November 25th, 2022
- [ ]  Make a detail rundown for the AMA
- [x] Create Meetup event @andreassosilo 
- [ ] Flyer created by Stevani

## Discussion

- Try to find speaker from Harmony Indonesia
- Create Meetup event in Cardano Blockchain Jakarta
